name: Cppcheck

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install cppcheck
      run: |
        sudo apt-get install cppcheck

    - name: Run cppcheck
      run: |
        cppcheck --enable=all --std=c++20 --platform=win64 --error-exitcode=1 --template="{file}:{line}: {severity}: {message}\n{code}" --template-location="{file}:{line}: note: {info}\n{code}" --inconclusive --force --suppress=missingIncludeSystem ./code/
